### ISSUE TITLE
PDF Bilder Worker

### ISSUE THREAD

**Issue by ekrebs5** [querenker/COAL#19]
- erkennt, ob Bilder vorhanden sind
- wenn ja, wie viele
- wenn ja, was darauf (clarifai)

**Comment by aloeser** [comment]
pdfimages gibt nicht aus, wie viele Bilder vorhanden sind. Man könnte manuell zählen, aber brauchen wir diese Daten?

**Comment by aloeser** [comment]
sollen die Bilder in nen extra Ordner oder direkt in den Cache?

**Comment by querenker** [comment]
Die Anzahl der Bilder könnte vielleicht genutzt werden um zu ermitteln, ob es sich um ein Paper handelt? Ansonsten wäre ein extra-Ordner bestimmt nicht schlecht, oder? Vielleicht sogar einen allgemeinen Bilder-Ordner und darin Unterorder für die einzelnen PDFs (benannt nach dem Hashwert?). Die Anzahl der Bilder könnte dann einfach durch das Zählen der Elemente im entsprechenden Order erfolgen?
