### ISSUE TITLE
Motivation Text

### ISSUE THREAD

**Issue by ekrebs5** [querenker/COAL#45]
WHAT do we do
WHY do we do it
HOW do we do it (idea)

**Comment by blblblu** [comment]
- COAL->Server, der Analyse und Extraktion von Metadaten aus Dateien dient
- ->Informationen können maschinenlesbar (-> RDF) anderen Diensten (z.B. Suchmaschinen) bereitgestellt werden, (bzw. Daten zu bestimmter Datei können vom Dienst bei COAL-Server angefragt werden)
- -> Spezialisierung auf PDFs, welche nun von verschiedenen Workern analysiert werden

**Comment by ekrebs5** [comment]
COAL is a service which analyses and extracts metadata for a requested resource. The request is sent to the COAL server, processed by COAL workers and the metadata collected in a rdf document.

This enables other services, e.g. search engines, to process the data more accurately.

Our team concentrated on pdf metadata extraction. We created new workers for pdfs and related data.
